-- Create table
CREATE TABLE BANK_ACCOUNT
(
  ID        BIGINT NOT NULL,
  FULL_NAME VARCHAR(128) NOT NULL,
  BALANCE   FLOAT NOT NULL
);

-- Add a primary key constraint
ALTER TABLE BANK_ACCOUNT
  ADD CONSTRAINT BANK_ACCOUNT_PK PRIMARY KEY (ID);

-- Insert data into BANK_ACCOUNT
INSERT INTO BANK_ACCOUNT(ID, FULL_NAME, BALANCE) VALUES (1, 'Tom', 1000);
INSERT INTO BANK_ACCOUNT(ID, FULL_NAME, BALANCE) VALUES (2, 'Jerry', 2000);
INSERT INTO BANK_ACCOUNT(ID, FULL_NAME, BALANCE) VALUES (3, 'Donald', 3000);
